### PR TITLE
Lps 94561

### PR DESCRIPTION
**Pull request by leomiyagi**

### CODE REVIEW

**Comment by vagnerbc** [comment]
Only the testJapanKanjiDialectSort () test is not passing.

Icu collation was able to solve the problem of sorting English, Portuguese, Spanish, French, German and Polish.

To order katana and hiragana was not necessary icu_collation.

**Comment by vagnerbc** [comment]
[index.txt](https://github.com/leomiyagi/liferay-portal/files/3397387/index.txt)

**Comment by leomiyagi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leomiyagi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/813. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
