### PR TITLE
LPS-86734 Integrate WikiPage and WikiNode to new indexer model.

### PR DESCRIPTION
**Pull request by luanmaoski**

### CODE REVIEW

**Comment by luanmaoski** [comment]
ci:test:search

**Comment by leomiyagi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leomiyagi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leomiyagi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/776. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
