### PR TITLE
LPS-97798 Spike ModelDocumentContributor

### PR DESCRIPTION
**Pull request by vagnerbc**
https://issues.liferay.com/browse/LPS-97798

### CODE REVIEW

**Comment by vagnerbc** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
ci:test:search

**Comment by leomiyagi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leomiyagi** [comment]
ci:test:search:norebase

**Comment by leomiyagi** [comment]
ci:test:sf:norebase

**Comment by leomiyagi** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/811. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
