### PR TITLE
LPS-90067 asset-service: Integrate AssetEntry to new indexer mode

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:sf:norebase

**Comment by brandizzi** [comment]
ci:test:search:norebase

**Comment by leomiyagi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leomiyagi** [comment]
brandizzi#773

**Pull request closed without merging**
